FEATURES = [
    {
        "name": "Checking Account",
        "type": "categorical",
        "categories": ["A11", "A12", "A13", "A14"],
        "explanation": "Status of the applicant's checking account balance.",
    },
    {
        "name": "Duration",
        "type": "numerical",
        "min": 4,
        "max": 72,
        "explanation": "Credit repayment duration in months.",
    },
    {
        "name": "Credit History",
        "type": "categorical",
        "categories": ["A30", "A31", "A32", "A33", "A34"],
        "explanation": "History of the applicant's credit behavior.",
    },
    {
        "name": "Purpose",
        "type": "categorical",
        "categories": ["A40", "A41", "A42", "A43", "A44", "A45", "A46", "A48"],
        "explanation": "Reason for taking the credit.",
    },
    {
        "name": "Credit Amount",
        "type": "numerical",
        "min": 250,
        "max": 20000,
        "explanation": "The amount of money the applicant wants to borrow.",
    },
    {
        "name": "Savings Account/Bonds",
        "type": "categorical",
        "categories": ["A61", "A62", "A63", "A64", "A65"],
        "explanation": "Status of savings account or bonds.",
    },
    {
        "name": "Present Employment Since",
        "type": "categorical",
        "categories": ["A71", "A72", "A73", "A74", "A75"],
        "explanation": "Number of years the applicant has been employed.",
    },
    {
        "name": "Instalment Rate",
        "type": "numerical",
        "min": 1,
        "max": 4,
        "explanation": "Monthly instalment as % of disposable income.",
    },
    {
        "name": "Personal Status",
        "type": "categorical",
        "categories": ["A91", "A92", "A93", "A94"],
        "explanation": "Applicant's marital status and gender.",
    },
    {
        "name": "Other Debtors",
        "type": "categorical",
        "categories": ["A101", "A102", "A103"],
        "explanation": "Other people responsible for the credit.",
    },
    {
        "name": "Present Residence",
        "type": "numerical",
        "min": 1,
        "max": 4,
        "explanation": "Number of years at current residence.",
    },
    {
        "name": "Property",
        "type": "categorical",
        "categories": ["A121", "A122", "A123", "A124"],
        "explanation": "Applicant's owned property used as collateral.",
    },
    {
        "name": "Age",
        "type": "numerical",
        "min": 18,
        "max": 75,
        "explanation": "Applicant's age in years.",
    },
    {
        "name": "Other Instalment Plans",
        "type": "categorical",
        "categories": ["A141", "A142", "A143"],
        "explanation": "Other concurrent instalment plans the applicant may have.",
    },
    {
        "name": "Housing",
        "type": "categorical",
        "categories": ["A151", "A152", "A153"],
        "explanation": "Applicant's housing status.",
    },
    {
        "name": "Existing Credits",
        "type": "numerical",
        "min": 1,
        "max": 4,
        "explanation": "Number of credits the applicant has with this bank.",
    },
    {
        "name": "Job",
        "type": "categorical",
        "categories": ["A171", "A172", "A173", "A174"],
        "explanation": "Applicant's occupation type.",
    },
    {
        "name": "Dependents",
        "type": "numerical",
        "min": 0,
        "max": 2,
        "explanation": "Number of dependents supported by the applicant.",
    },
    {
        "name": "Telephone",
        "type": "categorical",
        "categories": ["A191", "A192"],
        "explanation": "Whether applicant has a registered telephone.",
    },
    {
        "name": "Foreign Worker",
        "type": "categorical",
        "categories": ["A201", "A202"],
        "explanation": "Whether applicant is a foreign worker.",
    },
]
